바텀 네비게이션 컴포넌트 제작
PBTP/Mongle_Business pull request #5
Opened 2024-08-08 14:47 UTC by gbwlxhd97

## 🎫 [지라 티켓 번호] 후쿼카 이슈로 없음

## 🛠️ 작업 내용

![image](https://github.com/user-attachments/assets/bb724c1b-d56d-4fef-8748-2f57838d1511)

<br>
1. 바텀 네비게이션 컴포넌트를 제작했어요.
애니메이션 효과는 미미하나 나중에 좀 정확해지면 더 적용하려고 합니다.
2.추가적으로 웹뷰 토큰 로직을 제거하였고

<br>

## 🗒️ Note (optional)

2024-08-12 08:40 UTC, VictoryJu requested changes

2024-08-12 08:40 UTC, VictoryJu commented on src/router/ProtectedRoute.tsx
> +          <Outlet /> <BottomNavigation />
BottomNavigation 컴포넌트는 ProtectedRoute말고 RootLayout에 들어가야할것같습니다.

2024-08-12 08:40 UTC, VictoryJu commented on src/components/Layout/RootLayout/RootLayout.tsx
>      </div>
```suggestion
    <BottomNavigation/>
    </div>
```
요렇게 들어가야하지않을까싶네용

2024-08-12 08:40 UTC, VictoryJu commented on src/components/Layout/BottomNavigation/BottomNavigation.tsx
> +    <nav className={styles.BottomNavigationContainer}>
저는 Wrapper를 가장 큰 순위로 두기는 합니당ㅎㅎ

Wrapper > Container > Content > Line 요런느낌?

2024-08-12 08:40 UTC, VictoryJu commented on src/components/Layout/BottomNavigation/BottomNavigation.module.scss
> +    .label {
className은 대문자로 통일 어떠신가용?

2024-08-12 13:42 UTC, gbwlxhd97 commented on src/components/Layout/BottomNavigation/BottomNavigation.module.scss
> +    .label {
저건 지피티 시킨거라 수정했어야 했는데 ㅎㅎ
걸렸네여

2024-08-12 13:43 UTC, gbwlxhd97 commented on src/components/Layout/RootLayout/RootLayout.tsx
>      </div>
음 그러면 RootLayout에 들어가게 되면
로그인 정보 있을때만 보이게 처리하겠습니다!

2024-08-12 14:32 UTC, VictoryJu commented on src/components/Layout/RootLayout/RootLayout.tsx
>      </div>
아 피그마보니까 네비게이션이 있을때도있고 없을때도 있군요 좋습니다

2024-08-21 13:30 UTC, gbwlxhd97 commented
말씀하신 부분 다 수정해서 머지 하겠습니다!
@VictoryJu

2024-08-21 13:30 UTC, merged